default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bnh_development

test:
  <<: *default
  database: bnh_test

production:
  <<: *default
  database: bnh_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>